_target_: params.TrainConfig

model:
  _target_: params.ModelConfig
  model_path: 'models/output_model.pkl'
  metric_json_path: 'models/metrics/output_model_metrics.json'
  processed_data_path: 'data/processed/processed_data.csv'
  transformer_model_path: 'models/transformer.pkl'

  train_params:
    _target_: params.TrainingParams
    random_state: 42
    grid_search: true

input_data_path: 'data/raw/heart_cleveland_upload.csv'
test_data_path: 'data/test/heart_cleveland_upload_test.csv'

splitting_params:
  _target_: params.SplittingParams
  train_size: 0.8
  random_state: 42

feature_params:
  _target_: params.FeatureParams
  numerical:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  categorical:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  target: 'condition'

mlflow_run_name: 'classification'
mlflow_url: 'http://localhost:5000'
